usgs-site-service-url=https://waterservices.usgs.gov/nwis/site/?
usgs-daily-values-service-url=https://waterservices.usgs.gov/nwis/dv/?
usgs-instantaneous-values-service-url=https://waterservices.usgs.gov/nwis/iv/?