usgs-monitoring-locations-url=https://api.waterdata.usgs.gov/ogcapi/v0/collections/monitoring-locations/items?
usgs-time-series-metadata-url=https://api.waterdata.usgs.gov/ogcapi/v0/collections/time-series-metadata/items?
usgs-daily-url=https://api.waterdata.usgs.gov/ogcapi/v0/collections/daily/items?
usgs-continuous-url=https://api.waterdata.usgs.gov/ogcapi/v0/collections/continuous/items?
